### ISSUE TITLE
Submitting plugins upstream

### ISSUE THREAD

**Issue by djmattyg007** [pematon/adminer-plugins#2]
Have you considered submitting these plugins to the central adminer project?

**Comment by peterpp** [comment]
Maybe I can submit them directly to Adminer. I am not sure if 3-rd party plugins will be accepted. My AdminerJsonPreview is similar to https://github.com/vrana/adminer/blob/master/plugins/json-column.php, but much enhanced. At least, I can try :)

**Comment by djmattyg007** [comment]
I've submitted plugins to the upstream adminer project before. It's definitely worth trying, and at the very least you'll hopefully get some recommendations for improving the code.

**Comment by peterpp** [comment]
Adminer project has different coding style that I really don't like. So I decided not to submit my plugins there.

**Comment by djmattyg007** [comment]
Would you mind if I submitted them for you?

**Comment by peterpp** [comment]
If you'll keep copyright info, than you can try. But I think that better approach will be a link in "User contributed plugins" on https://www.adminer.org/en/plugins/
