### ISSUE TITLE
AdminerJsonPreview: please make MAX_TEXT_LENGTH configurable

### ISSUE THREAD

**Issue by Toutouwai** [pematon/adminer-plugins#6]
Discovered your Adminer theme and plugins today - love them!

In the AdminerJsonPreview plugin, could you please make the max text length configurable via the constructor the way that `$maxLevel`, `$inTable` and `$inEdit` are?

**Comment by peterpp** [comment]
Thank you 🙂
Max. text length is configurable now: https://github.com/pematon/adminer-plugins/commit/90d9a6afd31101b2393be9710d6bfd94d3f596af
Enjoy!

**Comment by Toutouwai** [comment]
Wonderful, thanks!
